#NoEnv
#SingleInstance Force
SetBatchLines, -1
SetWorkingDir, %A_ScriptDir%

script_version := "0.03"
test_root := A_ScriptDir

create_result := createTestTree( test_root )
verify_result := verifyTestTree( test_root )

result_text := "Path-Config test tree " script_version "`n`n"
result_text .= create_result.message "`n"
result_text .= verify_result.message

if ( create_result.success && verify_result.success )
{
    MsgBox, 64, Test Tree Created, %result_text%
    Run, explorer.exe "%test_root%"
}
else
{
    MsgBox, 16, Test Tree Error, %result_text%
}

ExitApp


/*
Creates the complete Path-Config test tree.
Returns an object containing success state and a status message.
*/
createTestTree( test_root )
{
    source_root := test_root "\Source"
    target_root := test_root "\Target"
    hardlink_source_dir := source_root "\hardlink-test"
    softlink_source_dir := source_root "\softlink-test"
    file_links_dir := source_root "\file-links"

    hardlink_source_file := hardlink_source_dir "\foo.txt"
    softlink_source_file := softlink_source_dir "\foo.txt"
    hardlink_test_file := file_links_dir "\hardlink-test.txt"
    junction_test_file := file_links_dir "\junction-test.txt"
    link_test_file := file_links_dir "\link-test.txt"
    legacy_shortcut_file := file_links_dir "\link-test.lnk"
    foo_exe_path := source_root "\foo.exe"

    if ( !cleanupTestRoot( source_root ) || !cleanupTestRoot( target_root ) )
    {
        return {"success":false, "message":"Failed to clean existing Source or Target directories."}
    }

    FileCreateDir, %hardlink_source_dir%
    FileCreateDir, %softlink_source_dir%
    FileCreateDir, %file_links_dir%
    FileCreateDir, %target_root%

    if ( ErrorLevel )
    {
        return {"success":false, "message":"Failed to create one or more test directories."}
    }

    if ( !writeTextFile( hardlink_source_file, "Hard-link source file.`r`n" ) )
    {
        return {"success":false, "message":"Failed to create hardlink-test\\foo.txt."}
    }

    if ( !writeTextFile( softlink_source_file, "Shortcut source file.`r`n" ) )
    {
        return {"success":false, "message":"Failed to create softlink-test\\foo.txt."}
    }

    if ( !createTestExecutable( foo_exe_path ) )
    {
        return {"success":false, "message":"Failed to create foo.exe from Windows Notepad."}
    }

    deleteLegacyLink( hardlink_test_file, false )
    deleteLegacyLink( junction_test_file, true )
    deleteLegacyLink( legacy_shortcut_file, false )

    if ( !writeTextFile( hardlink_test_file, "Hard-link test file.`r`n" ) )
    {
        return {"success":false, "message":"Failed to create hardlink-test.txt."}
    }

    if ( !writeTextFile( junction_test_file, "Junction test file.`r`n" ) )
    {
        return {"success":false, "message":"Failed to create junction-test.txt."}
    }

    if ( !writeTextFile( link_test_file, "Shortcut test file.`r`n" ) )
    {
        return {"success":false, "message":"Failed to create link-test.txt."}
    }

    return {"success":true, "message":"Creation: PASS"}
}


/*
Writes a text file and replaces any previous file at the same path.
Returns true when the file exists after writing.
*/
writeTextFile( file_path, file_text )
{
    FileDelete, %file_path%
    FileAppend, %file_text%, %file_path%

    return FileExist( file_path ) ? true : false
}


/*
Removes link objects generated by earlier versions without touching their targets.
*/
deleteLegacyLink( link_path, is_directory )
{
    if ( !FileExist( link_path ) )
    {
        return true
    }

    if ( is_directory )
    {
        RunWait, %ComSpec% /D /C rmdir "%link_path%",, Hide UseErrorLevel
        return ( ErrorLevel = 0 )
    }

    FileDelete, %link_path%

    return !FileExist( link_path )
}

/*
Removes a previously generated test root so the tree is rebuilt from scratch.
Returns true when the directory no longer exists.
*/
cleanupTestRoot( root_path )
{
    if ( !FileExist( root_path ) )
    {
        return true
    }

    FileRemoveDir, %root_path%, 1

    return !FileExist( root_path )
}

/*
Copies Windows Notepad as a harmless valid test executable.
Returns true when foo.exe was created.
*/
createTestExecutable( target_path )
{
    source_exe := A_WinDir "\System32\notepad.exe"
    FileDelete, %target_path%
    FileCopy, %source_exe%, %target_path%, 1

    return FileExist( target_path ) ? true : false
}


/*
Verifies the generated tree and its expected fixture files.
Returns a combined status message suitable for a test result dialog.
*/
verifyTestTree( test_root )
{
    source_root := test_root "\Source"
    target_root := test_root "\Target"
    hardlink_source_file := source_root "\hardlink-test\foo.txt"
    softlink_source_file := source_root "\softlink-test\foo.txt"
    hardlink_test_file := source_root "\file-links\hardlink-test.txt"
    junction_test_file := source_root "\file-links\junction-test.txt"
    link_test_file := source_root "\file-links\link-test.txt"
    foo_exe_path := source_root "\foo.exe"

    error_text := ""

    verifyPathExists( source_root, "Directory Source", error_text )
    verifyPathExists( target_root, "Directory Target", error_text )
    verifyPathExists( hardlink_source_file, "hardlink-test\\foo.txt", error_text )
    verifyPathExists( softlink_source_file, "softlink-test\\foo.txt", error_text )
    verifyPathExists( hardlink_test_file, "file-links\\hardlink-test.txt", error_text )
    verifyPathExists( junction_test_file, "file-links\\junction-test.txt", error_text )
    verifyPathExists( link_test_file, "file-links\\link-test.txt", error_text )
    verifyPathExists( foo_exe_path, "foo.exe", error_text )

    if ( error_text != "" )
    {
        return {"success":false, "message":"Verification: FAIL" error_text}
    }

    return {"success":true, "message":"Verification: PASS"}
}


/*
Adds an error when an expected file or directory is missing.
The error string is passed by reference.
*/
verifyPathExists( file_path, display_name, ByRef error_text )
{
    if ( !FileExist( file_path ) )
    {
        error_text .= "`nMissing: " display_name
    }

    ; return
}
